services:
  authentication_postgres:
    image: postgres
    restart: always
    env_file:
      - ./authentication/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  authentication_service:
    build:
      dockerfile: authentication/deploy/Dockerfile
      args:
        REQUIREMENTS: deploy/requirements/develop.txt
    env_file:
      - ./authentication/.env
    ports:
      - "8000:8000"
    depends_on:
      - authentication_postgres
#      - authentication_front
    volumes:
      - ./authentication:/code
    command: bash -c "
      python migrate.py head &&
      uvicorn app:app --host 0.0.0.0 --port 8000 --reload"

#  authentication_front:
#    build:
#      dockerfile: authentication_front/Dockerfile
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./authentication_front:/code
#      - /code/node_modules

volumes:
  postgres_data: null
